### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by eserte** [pplu/docker-registry#1]
It seems that some dependencies are not declared as prereqs:
* Test::Exception
* Paws

Also it does not work with older perl versions, so the minimum perl version should also be increased (or the problem fixed by using an old-fashioned package declaration):
```
syntax error at t/02_ecr.t line 13, near "package TestIO::Fake {
  "
Execution of t/02_ecr.t aborted due to compilation errors.
t/02_ecr.t .. 
```

**Comment by pplu** [comment]
Hi. Just uploaded 0.03 to CPAN with your suggested changes. Thanks!
